In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3,4 ])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
zeros_arr = np.zeros((2,2))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones_arr = np.ones((3, 2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arange_arr = np.arange(0, 20, 3)
arange_arr


[ 0  3  6  9 12 15 18]


In [ ]:
linspace_arr = np.linspace(0, 1000, 6)
linspace_arr

array([   0.,  200.,  400.,  600.,  800., 1000.])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_arr = a + b
sum_arr

array([5, 7, 9])

In [ ]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[1, 2], [3, 4]])
product_matrix = np.dot(matrix_a, matrix_b)
product_matrix

array([[ 7, 10],
       [15, 22]])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
sub_arr = arr[2:5]
sub_arr


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
total_sum



3.0

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
mean_value

3.0

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr)
std_dev

1.4142135623730951

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])
reshaped_arr = arr.reshape((3, 3))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
original_matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = np.transpose(original_matrix)
transposed_matrix

array([[1, 3],
       [2, 4]])